language: python
python:
  - '2.7'
  - '3.4'
script: py.test
notifications:
  slack:
    secure: PN65rOZLRze8RMWuokn5oDJwfnDuVpEgeP9xOx1y22TY77qtqtFeEpizbAr0tJDI/6PcInGm2SYyhsz3uEc5BqWAOjkP4yuvkj0ZEoFYiUHcuGNSdemQxTi03CiMF6ZbIENsrGkeeLLp2TlNoHhd5Gm4e5wnMA9hz5V1h5wt0wM=
